FROM px4io/px4-dev-simulation-jammy:latest

RUN pip3 install symforce
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    cmake \
    pkg-config \
    libfreeimage-dev \
    libtinyxml2-dev \
    uuid-dev \
    libgts-dev \
    libzip-dev \
    libjsoncpp-dev \
    libcurl4-openssl-dev \
    libyaml-dev \
    libavdevice-dev \
    libavformat-dev \
    libavcodec-dev \
    libswscale-dev \
    libavutil-dev \
    libprotoc-dev \
    libprotobuf-dev \
    protobuf-compiler \
    mesa-utils \
    lsb-release \
    wget \
    gnupg \
    libboost-system-dev \
    libtinyxml-dev \
    libxml2-utils \
    ruby-dev \
    ruby

RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

RUN apt-get update
RUN apt-get install -y \
    gz-harmonic \
    libgz-transport13-dev
